// MongoDB "DDL" initialize the "{{ dbname }}" database and its collections.
//
// Generated on: {{ gen_timestamp }}
// Generated by: {{ gen_by }}
// Template:     mongo_database_init.ddl
// TODO:         customer to add indexes as necessary

use {{ dbname }}

{% for c in collections -%}
db.{{ c }}.drop()
db.createCollection("{{ c }}")
// db.{{ c }}.ensureIndex({"some_attribute" : 1}, {"unique" : false})

{% endfor %}
show collections