#!/bin/bash

# bash script to execute the mongo command-line program, redirecting
# in a "ddl" file to create the collections and indexes in the target
# Cosmos/Mongo database.
#
# Generated on: 2021-06-07 16:48:15 UTC
# Generated by: artifact_generator.py gen_target_cosmos_init()
# Template:     mongo_database_init.txt

source env.sh

echo 'init database olympics ...'
mongo $M2C_COSMOS_MONGO_CONN_STRING --ssl < mongo/mongo_init_olympics_db.ddl
