#!/bin/bash

# bash script to execute the mongo CLI program to create and load
# the localhost olympics database.  This database is then used
# as a reference database for the migration process in this repo.
# Chris Joakim, Microsoft, May 2021

echo 'init ...'
mongo localhost:27017/olympics < mongo/olympics_init.ddl

echo 'mongoimport games ...'
mongoimport --db olympics \
    --collection games \
    --file olympics/import_json/games.json \
    --numInsertionWorkers 1 \
    --batchSize 24

echo 'mongoimport countries ...'
mongoimport --db olympics \
    --collection countries \
    --file olympics/import_json/countries.json \
    --numInsertionWorkers 1 \
    --batchSize 24

# The following generated by: python main.py generate_games_import_commands

echo 'importing game g1896_summer'
mongoimport --db olympics \
    --collection g1896_summer \
    --file olympics/import_json/1896_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1900_summer'
mongoimport --db olympics \
    --collection g1900_summer \
    --file olympics/import_json/1900_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1904_summer'
mongoimport --db olympics \
    --collection g1904_summer \
    --file olympics/import_json/1904_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1906_summer'
mongoimport --db olympics \
    --collection g1906_summer \
    --file olympics/import_json/1906_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1908_summer'
mongoimport --db olympics \
    --collection g1908_summer \
    --file olympics/import_json/1908_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1912_summer'
mongoimport --db olympics \
    --collection g1912_summer \
    --file olympics/import_json/1912_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1920_summer'
mongoimport --db olympics \
    --collection g1920_summer \
    --file olympics/import_json/1920_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1924_summer'
mongoimport --db olympics \
    --collection g1924_summer \
    --file olympics/import_json/1924_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1924_winter'
mongoimport --db olympics \
    --collection g1924_winter \
    --file olympics/import_json/1924_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1928_summer'
mongoimport --db olympics \
    --collection g1928_summer \
    --file olympics/import_json/1928_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1928_winter'
mongoimport --db olympics \
    --collection g1928_winter \
    --file olympics/import_json/1928_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1932_summer'
mongoimport --db olympics \
    --collection g1932_summer \
    --file olympics/import_json/1932_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1932_winter'
mongoimport --db olympics \
    --collection g1932_winter \
    --file olympics/import_json/1932_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1936_summer'
mongoimport --db olympics \
    --collection g1936_summer \
    --file olympics/import_json/1936_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1936_winter'
mongoimport --db olympics \
    --collection g1936_winter \
    --file olympics/import_json/1936_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1948_summer'
mongoimport --db olympics \
    --collection g1948_summer \
    --file olympics/import_json/1948_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1948_winter'
mongoimport --db olympics \
    --collection g1948_winter \
    --file olympics/import_json/1948_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1952_summer'
mongoimport --db olympics \
    --collection g1952_summer \
    --file olympics/import_json/1952_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1952_winter'
mongoimport --db olympics \
    --collection g1952_winter \
    --file olympics/import_json/1952_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1956_summer'
mongoimport --db olympics \
    --collection g1956_summer \
    --file olympics/import_json/1956_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1956_winter'
mongoimport --db olympics \
    --collection g1956_winter \
    --file olympics/import_json/1956_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1960_summer'
mongoimport --db olympics \
    --collection g1960_summer \
    --file olympics/import_json/1960_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1960_winter'
mongoimport --db olympics \
    --collection g1960_winter \
    --file olympics/import_json/1960_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1964_summer'
mongoimport --db olympics \
    --collection g1964_summer \
    --file olympics/import_json/1964_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1964_winter'
mongoimport --db olympics \
    --collection g1964_winter \
    --file olympics/import_json/1964_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1968_summer'
mongoimport --db olympics \
    --collection g1968_summer \
    --file olympics/import_json/1968_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1968_winter'
mongoimport --db olympics \
    --collection g1968_winter \
    --file olympics/import_json/1968_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1972_summer'
mongoimport --db olympics \
    --collection g1972_summer \
    --file olympics/import_json/1972_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1972_winter'
mongoimport --db olympics \
    --collection g1972_winter \
    --file olympics/import_json/1972_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1976_summer'
mongoimport --db olympics \
    --collection g1976_summer \
    --file olympics/import_json/1976_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1976_winter'
mongoimport --db olympics \
    --collection g1976_winter \
    --file olympics/import_json/1976_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1980_summer'
mongoimport --db olympics \
    --collection g1980_summer \
    --file olympics/import_json/1980_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1980_winter'
mongoimport --db olympics \
    --collection g1980_winter \
    --file olympics/import_json/1980_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1984_summer'
mongoimport --db olympics \
    --collection g1984_summer \
    --file olympics/import_json/1984_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1984_winter'
mongoimport --db olympics \
    --collection g1984_winter \
    --file olympics/import_json/1984_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1988_summer'
mongoimport --db olympics \
    --collection g1988_summer \
    --file olympics/import_json/1988_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1988_winter'
mongoimport --db olympics \
    --collection g1988_winter \
    --file olympics/import_json/1988_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1992_summer'
mongoimport --db olympics \
    --collection g1992_summer \
    --file olympics/import_json/1992_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1992_winter'
mongoimport --db olympics \
    --collection g1992_winter \
    --file olympics/import_json/1992_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1994_winter'
mongoimport --db olympics \
    --collection g1994_winter \
    --file olympics/import_json/1994_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1996_summer'
mongoimport --db olympics \
    --collection g1996_summer \
    --file olympics/import_json/1996_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g1998_winter'
mongoimport --db olympics \
    --collection g1998_winter \
    --file olympics/import_json/1998_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2000_summer'
mongoimport --db olympics \
    --collection g2000_summer \
    --file olympics/import_json/2000_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2002_winter'
mongoimport --db olympics \
    --collection g2002_winter \
    --file olympics/import_json/2002_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2004_summer'
mongoimport --db olympics \
    --collection g2004_summer \
    --file olympics/import_json/2004_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2006_winter'
mongoimport --db olympics \
    --collection g2006_winter \
    --file olympics/import_json/2006_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2008_summer'
mongoimport --db olympics \
    --collection g2008_summer \
    --file olympics/import_json/2008_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2010_winter'
mongoimport --db olympics \
    --collection g2010_winter \
    --file olympics/import_json/2010_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2012_summer'
mongoimport --db olympics \
    --collection g2012_summer \
    --file olympics/import_json/2012_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2014_winter'
mongoimport --db olympics \
    --collection g2014_winter \
    --file olympics/import_json/2014_winter.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'importing game g2016_summer'
mongoimport --db olympics \
    --collection g2016_summer \
    --file olympics/import_json/2016_summer.json \
    --numInsertionWorkers 1 \
    --batchSize 24
sleep 3

echo 'done'
